name: Run Happo on PR comment
on:
  issue_comment:
    types:
      - created

jobs:
  run-happo:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'run happo now' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get pull request branches
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_number = context.payload.issue.number;
            const { owner, repo } = context.repo;

            async function getPullRequestBranches() {
              const response = await github.rest.pulls.get({
                owner,
                repo,
                pull_number,
              });

              const baseBranch = response.data.base.ref;
              const headBranch = response.data.head.ref;

              return { baseBranch, headBranch };
            }

            const branches = await getPullRequestBranches();
            console.log("Base Branch:", branches.baseBranch);
            console.log("Head Branch:", branches.headBranch);

            // Set environment variables
            process.env.PREVIOUS_SHA = branches.baseBranch;
            process.env.CURRENT_SHA = branches.headBranch;
            process.env.CHANGE_URL = context.payload.issue.html_url;
