name: Run Happo on PR comment
on:
  issue_comment:
    types:
      - created

jobs:
  run-happo:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'run happo now' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get pull request branches
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_number = context.payload.issue.number;
            const { owner, repo } = context.repo;

            async function getPullRequestInfo() {
              const response = await github.rest.pulls.get({
                owner,
                repo,
                pull_number,
              });

              const previousSHA = response.data.base.sha;
              const currentSHA = response.data.head.sha;
              const changeURL = response.data.html_url;

              return { previousSHA, currentSHA, changeURL };
            }

            return getPullRequestInfo();

      - name: Set output variables
        id: set_output_variables
        run: |
          echo "::set-output name=previousSHA::${{ steps.get_pull_request_info.outputs.previousSHA }}"
          echo "::set-output name=currentSHA::${{ steps.get_pull_request_info.outputs.currentSHA }}"
          echo "::set-output name=changeURL::${{ steps.get_pull_request_info.outputs.changeURL }}"

      - name: Display environment variables
        run: |
          echo "PREVIOUS SHA: ${{ steps.set_output_variables.outputs.previousSHA }}"
          echo "CURRENT SHA: ${{ steps.set_output_variables.outputs.currentSHA }}"
          echo "CHANGE URL: ${{ steps.set_output_variables.outputs.changeURL }}"
