name: Run Happo on PR comment
on:
  issue_comment:
    types:
      - created

jobs:
  run-happo:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'run happo now' }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR info to env
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_INFO=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL)
          echo "CHANGE_URL=${PR_URL}" >> $GITHUB_ENV
          BASE_BRANCH=$(echo "$PR_INFO" | jq -r '.base.ref')
          LAST_COMMIT_SHA_BASE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/$BASE_BRANCH" | jq -r '.sha')
          echo "PREVIOUS_SHA=${LAST_COMMIT_SHA_BASE}" >> $GITHUB_ENV
          LAST_COMMIT_SHA_HEAD=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL/commits | jq -r '.[-1].sha')
          echo "CURRENT_SHA=${LAST_COMMIT_SHA_HEAD}" >> $GITHUB_ENV
      - name: Display env
        run: |
          echo "CHANGE_URL=$CHANGE_URL"
          echo "PREVIOUS_SHA=$PREVIOUS_SHA"
          echo "CURRENT_SHA=$CURRENT_SHA"
